In [12]:
import pandas as pd

# Définir les chemins d'accès des fichiers
file1 = "C:\\Users\\DOUMBIA\\Desktop\\Base_économ\\export-2024-12-13T15_11_04.315Z.csv"
file2 = "C:\\Users\\DOUMBIA\\Desktop\\Base_économ\\export-2024-12-13T15_09_45.951Z.csv"
file3 = "C:\\Users\\DOUMBIA\\Desktop\\Base_économ\\API_SE.XPD.TOTL.GD.ZS_DS2_fr_csv_v2_45890\\API_SE.XPD.TOTL.GD.ZS_DS2_fr_csv_v2_45890.csv"
file4 = "C:\\Users\\DOUMBIA\\Desktop\\Base_économ\\API_NY.GDP.PCAP.CD_DS2_fr_csv_v2_3034\\API_NY.GDP.PCAP.CD_DS2_fr_csv_v2_3034.csv"

# Importation des fichiers CSV
data1 = pd.read_csv(file1, sep=';', skiprows=2)  # Data 1 (commence à la ligne 3)
data2 = pd.read_csv(file2, sep=';', skiprows=2)  # Data 2 (commence à la ligne 3)
data3 = pd.read_csv(file3, sep=';', skiprows=4)  # Data 3 (commence à la ligne 5)
data4 = pd.read_csv(file4, sep=';', skiprows=4)  # Data 4 (commence à la ligne 5)

# Suppression des colonnes inutiles
data1_clean = data1.loc[:, ~data1.columns.str.contains('^Unnamed')]
data2_clean = data2.loc[:, ~data2.columns.str.contains('^Unnamed')]
data3_clean = data3.loc[:, ~data3.columns.str.contains('^Unnamed')]
data4_clean = data4.loc[:, ~data4.columns.str.contains('^Unnamed')]

# Affichage des premières lignes pour vérifier l'importation
print("Data1 - Aperçu:")
print(data1_clean.head())

print("\nData2 - Aperçu:")
print(data2_clean.head())

print("\nData3 - Aperçu:")
print(data3_clean.head())

print("\nData4 - Aperçu:")
print(data4_clean.head())

Data1 - Aperçu:
     Category Dépenses de santé
0  États-Unis         12555,264
1      Suisse           8049,11
2   Allemagne          8010,935
3     Norvège          7771,165
4    Autriche          7275,354

Data2 - Aperçu:
    Category Espérance de vie à la naissance
0      Japon                            84,1
1     Suisse                            83,7
2    Espagne                            83,2
3  Australie                            83,2
4      Suède                            83,1

Data3 - Aperçu:
  Country Name,"Country Code","Indicator Name","Indicator Code","1960","1961","1962","1963","1964","1965","1966","1967","1968","1969","1970","1971","1972","1973","1974","1975","1976","1977","1978","1979","1980","1981","1982","1983","1984","1985","1986","1987","1988","1989","1990","1991","1992","1993","1994","1995","1996","1997","1998","1999","2000","2001","2002","2003","2004","2005","2006","2007","2008","2009","2010","2011","2012","2013","2014","2015","2016","2017","2018","2019","2020","2021","2022","2023",
0  Aruba,"ABW","Dépenses publiques en éducation (...
1  ,"AFE","Dépenses publiques en éducation (% du ...
2  Afghanistan,"AFG","Dépenses publiques en éduca...
3  ,"AFW","Dépenses publiques en éducation (% du ...
4  Angola,"AGO","Dépenses publiques en éducation ...

Data4 - Aperçu:
  Country Name,"Country Code","Indicator Name","Indicator Code","1960","1961","1962","1963","1964","1965","1966","1967","1968","1969","1970","1971","1972","1973","1974","1975","1976","1977","1978","1979","1980","1981","1982","1983","1984","1985","1986","1987","1988","1989","1990","1991","1992","1993","1994","1995","1996","1997","1998","1999","2000","2001","2002","2003","2004","2005","2006","2007","2008","2009","2010","2011","2012","2013","2014","2015","2016","2017","2018","2019","2020","2021","2022","2023",
0  Aruba,"ABW","PIB par habitant ($ US courants)"...
1  ,"AFE","PIB par habitant ($ US courants)","NY....
2  Afghanistan,"AFG","PIB par habitant ($ US cour...
3  ,"AFW","PIB par habitant ($ US courants)","NY....
4  Angola,"AGO","PIB par habitant ($ US courants)...

In [16]:
# Afficher les colonnes de data3_clean et data4_clean pour vérifier les noms
print("Colonnes de data3_clean :", data3_clean.columns)
print("Colonnes de data4_clean :", data4_clean.columns)

# Suppression des colonnes inutiles si elles existent
columns_to_drop_data3 = ['Country Code', 'Indicator Code']
columns_to_drop_data4 = ['Country Code', 'Indicator Code']

# Vérification et suppression des colonnes uniquement si elles existent
data3_clean = data3_clean.drop(columns=[col for col in columns_to_drop_data3 if col in data3_clean.columns], errors='ignore')
data4_clean = data4_clean.drop(columns=[col for col in columns_to_drop_data4 if col in data4_clean.columns], errors='ignore')

# Renommer les colonnes pour une meilleure lisibilité
data3_clean.rename(columns={'Country Name': 'Country', 'Indicator Name': 'Indicator'}, inplace=True)
data4_clean.rename(columns={'Country Name': 'Country', 'Indicator Name': 'Indicator'}, inplace=True)

# Afficher les premières lignes après nettoyage
print("\nData3 - Nettoyée:")
print(data3_clean.head())

print("\nData4 - Nettoyée:")
print(data4_clean.head())

Colonnes de data3_clean : Index(['Country Name,"Country Code","Indicator Name","Indicator Code","1960","1961","1962","1963","1964","1965","1966","1967","1968","1969","1970","1971","1972","1973","1974","1975","1976","1977","1978","1979","1980","1981","1982","1983","1984","1985","1986","1987","1988","1989","1990","1991","1992","1993","1994","1995","1996","1997","1998","1999","2000","2001","2002","2003","2004","2005","2006","2007","2008","2009","2010","2011","2012","2013","2014","2015","2016","2017","2018","2019","2020","2021","2022","2023",'], dtype='object')
Colonnes de data4_clean : Index(['Country Name,"Country Code","Indicator Name","Indicator Code","1960","1961","1962","1963","1964","1965","1966","1967","1968","1969","1970","1971","1972","1973","1974","1975","1976","1977","1978","1979","1980","1981","1982","1983","1984","1985","1986","1987","1988","1989","1990","1991","1992","1993","1994","1995","1996","1997","1998","1999","2000","2001","2002","2003","2004","2005","2006","2007","2008","2009","2010","2011","2012","2013","2014","2015","2016","2017","2018","2019","2020","2021","2022","2023",'], dtype='object')

Data3 - Nettoyée:
  Country Name,"Country Code","Indicator Name","Indicator Code","1960","1961","1962","1963","1964","1965","1966","1967","1968","1969","1970","1971","1972","1973","1974","1975","1976","1977","1978","1979","1980","1981","1982","1983","1984","1985","1986","1987","1988","1989","1990","1991","1992","1993","1994","1995","1996","1997","1998","1999","2000","2001","2002","2003","2004","2005","2006","2007","2008","2009","2010","2011","2012","2013","2014","2015","2016","2017","2018","2019","2020","2021","2022","2023",
0  Aruba,"ABW","Dépenses publiques en éducation (...
1  ,"AFE","Dépenses publiques en éducation (% du ...
2  Afghanistan,"AFG","Dépenses publiques en éduca...
3  ,"AFW","Dépenses publiques en éducation (% du ...
4  Angola,"AGO","Dépenses publiques en éducation ...

Data4 - Nettoyée:
  Country Name,"Country Code","Indicator Name","Indicator Code","1960","1961","1962","1963","1964","1965","1966","1967","1968","1969","1970","1971","1972","1973","1974","1975","1976","1977","1978","1979","1980","1981","1982","1983","1984","1985","1986","1987","1988","1989","1990","1991","1992","1993","1994","1995","1996","1997","1998","1999","2000","2001","2002","2003","2004","2005","2006","2007","2008","2009","2010","2011","2012","2013","2014","2015","2016","2017","2018","2019","2020","2021","2022","2023",
0  Aruba,"ABW","PIB par habitant ($ US courants)"...
1  ,"AFE","PIB par habitant ($ US courants)","NY....
2  Afghanistan,"AFG","PIB par habitant ($ US cour...
3  ,"AFW","PIB par habitant ($ US courants)","NY....
4  Angola,"AGO","PIB par habitant ($ US courants)...

In [17]:
# Nettoyer les noms des colonnes en supprimant les guillemets et les virgules
data3_clean.columns = data3_clean.columns.str.replace('"', '').str.strip()
data4_clean.columns = data4_clean.columns.str.replace('"', '').str.strip()

# Vérification des nouvelles colonnes
print("\nColonnes de data3_clean après nettoyage:", data3_clean.columns)
print("\nColonnes de data4_clean après nettoyage:", data4_clean.columns)

# Suppression des colonnes inutiles si elles existent
columns_to_drop_data3 = ['Country Code', 'Indicator Code']
columns_to_drop_data4 = ['Country Code', 'Indicator Code']

# Suppression des colonnes
data3_clean = data3_clean.drop(columns=[col for col in columns_to_drop_data3 if col in data3_clean.columns], errors='ignore')
data4_clean = data4_clean.drop(columns=[col for col in columns_to_drop_data4 if col in data4_clean.columns], errors='ignore')

# Renommer les colonnes restantes pour plus de clarté
data3_clean.rename(columns={'Country Name': 'Country', 'Indicator Name': 'Indicator'}, inplace=True)
data4_clean.rename(columns={'Country Name': 'Country', 'Indicator Name': 'Indicator'}, inplace=True)

# Afficher les premières lignes après nettoyage
print("\nData3 - Nettoyée:")
print(data3_clean.head())

print("\nData4 - Nettoyée:")
print(data4_clean.head())

Colonnes de data3_clean après nettoyage: Index(['Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,1966,1967,1968,1969,1970,1971,1972,1973,1974,1975,1976,1977,1978,1979,1980,1981,1982,1983,1984,1985,1986,1987,1988,1989,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023,'], dtype='object')

Colonnes de data4_clean après nettoyage: Index(['Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,1966,1967,1968,1969,1970,1971,1972,1973,1974,1975,1976,1977,1978,1979,1980,1981,1982,1983,1984,1985,1986,1987,1988,1989,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023,'], dtype='object')

Data3 - Nettoyée:
  Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,1966,1967,1968,1969,1970,1971,1972,1973,1974,1975,1976,1977,1978,1979,1980,1981,1982,1983,1984,1985,1986,1987,1988,1989,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023,
0  Aruba,"ABW","Dépenses publiques en éducation (...
1  ,"AFE","Dépenses publiques en éducation (% du ...
2  Afghanistan,"AFG","Dépenses publiques en éduca...
3  ,"AFW","Dépenses publiques en éducation (% du ...
4  Angola,"AGO","Dépenses publiques en éducation ...

Data4 - Nettoyée:
  Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,1966,1967,1968,1969,1970,1971,1972,1973,1974,1975,1976,1977,1978,1979,1980,1981,1982,1983,1984,1985,1986,1987,1988,1989,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023,
0  Aruba,"ABW","PIB par habitant ($ US courants)"...
1  ,"AFE","PIB par habitant ($ US courants)","NY....
2  Afghanistan,"AFG","PIB par habitant ($ US cour...
3  ,"AFW","PIB par habitant ($ US courants)","NY....
4  Angola,"AGO","PIB par habitant ($ US courants)...

In [18]:
# Nettoyer les noms des colonnes en supprimant les guillemets, les virgules et les espaces superflus
data3_clean.columns = data3_clean.columns.str.replace(r'"|,', '', regex=True).str.strip()
data4_clean.columns = data4_clean.columns.str.replace(r'"|,', '', regex=True).str.strip()

# Vérification des nouvelles colonnes après nettoyage
print("\nColonnes de data3_clean après nettoyage:", data3_clean.columns)
print("\nColonnes de data4_clean après nettoyage:", data4_clean.columns)

# Suppression des colonnes inutiles si elles existent
columns_to_drop_data3 = ['Country Code', 'Indicator Code']
columns_to_drop_data4 = ['Country Code', 'Indicator Code']

# Suppression des colonnes
data3_clean = data3_clean.drop(columns=[col for col in columns_to_drop_data3 if col in data3_clean.columns], errors='ignore')
data4_clean = data4_clean.drop(columns=[col for col in columns_to_drop_data4 if col in data4_clean.columns], errors='ignore')

# Renommer les colonnes restantes pour plus de clarté
data3_clean.rename(columns={'Country Name': 'Country', 'Indicator Name': 'Indicator'}, inplace=True)
data4_clean.rename(columns={'Country Name': 'Country', 'Indicator Name': 'Indicator'}, inplace=True)

# Afficher les premières lignes après nettoyage
print("\nData3 - Nettoyée:")
print(data3_clean.head())

print("\nData4 - Nettoyée:")
print(data4_clean.head())

Colonnes de data3_clean après nettoyage: Index(['Country NameCountry CodeIndicator NameIndicator Code1960196119621963196419651966196719681969197019711972197319741975197619771978197919801981198219831984198519861987198819891990199119921993199419951996199719981999200020012002200320042005200620072008200920102011201220132014201520162017201820192020202120222023'], dtype='object')

Colonnes de data4_clean après nettoyage: Index(['Country NameCountry CodeIndicator NameIndicator Code1960196119621963196419651966196719681969197019711972197319741975197619771978197919801981198219831984198519861987198819891990199119921993199419951996199719981999200020012002200320042005200620072008200920102011201220132014201520162017201820192020202120222023'], dtype='object')

Data3 - Nettoyée:
  Country NameCountry CodeIndicator NameIndicator Code1960196119621963196419651966196719681969197019711972197319741975197619771978197919801981198219831984198519861987198819891990199119921993199419951996199719981999200020012002200320042005200620072008200920102011201220132014201520162017201820192020202120222023
0  Aruba,"ABW","Dépenses publiques en éducation (...
1  ,"AFE","Dépenses publiques en éducation (% du ...
2  Afghanistan,"AFG","Dépenses publiques en éduca...
3  ,"AFW","Dépenses publiques en éducation (% du ...
4  Angola,"AGO","Dépenses publiques en éducation ...

Data4 - Nettoyée:
  Country NameCountry CodeIndicator NameIndicator Code1960196119621963196419651966196719681969197019711972197319741975197619771978197919801981198219831984198519861987198819891990199119921993199419951996199719981999200020012002200320042005200620072008200920102011201220132014201520162017201820192020202120222023
0  Aruba,"ABW","PIB par habitant ($ US courants)"...
1  ,"AFE","PIB par habitant ($ US courants)","NY....
2  Afghanistan,"AFG","PIB par habitant ($ US cour...
3  ,"AFW","PIB par habitant ($ US courants)","NY....
4  Angola,"AGO","PIB par habitant ($ US courants)...

In [19]:
# Vérifier les noms des colonnes
print("\nColonnes de data3_clean après nettoyage (avant correction):")
print(data3_clean.columns)

print("\nColonnes de data4_clean après nettoyage (avant correction):")
print(data4_clean.columns)

# Séparer les noms de colonnes qui semblent fusionnés (s'il y en a)
# Si la concaténation est due à des virgules ou d'autres caractères, on peut les séparer
data3_clean.columns = data3_clean.columns.str.split(',').str[0]  # On garde la première partie
data4_clean.columns = data4_clean.columns.str.split(',').str[0]  # On garde la première partie

# Vérification après séparation des colonnes
print("\nColonnes de data3_clean après séparation:")
print(data3_clean.columns)

print("\nColonnes de data4_clean après séparation:")
print(data4_clean.columns)

# Nettoyer et renommer les colonnes de manière appropriée
data3_clean.columns = data3_clean.columns.str.replace(r'"|,', '', regex=True).str.strip()
data4_clean.columns = data4_clean.columns.str.replace(r'"|,', '', regex=True).str.strip()

# Supprimer les colonnes inutiles (par exemple, Country Code, Indicator Code si nécessaire)
columns_to_drop_data3 = ['Country Code', 'Indicator Code']
columns_to_drop_data4 = ['Country Code', 'Indicator Code']

data3_clean = data3_clean.drop(columns=[col for col in columns_to_drop_data3 if col in data3_clean.columns], errors='ignore')
data4_clean = data4_clean.drop(columns=[col for col in columns_to_drop_data4 if col in data4_clean.columns], errors='ignore')

# Renommer les colonnes 'Country Name' et 'Indicator Name' en 'Country' et 'Indicator' respectivement
data3_clean.rename(columns={'Country Name': 'Country', 'Indicator Name': 'Indicator'}, inplace=True)
data4_clean.rename(columns={'Country Name': 'Country', 'Indicator Name': 'Indicator'}, inplace=True)

# Afficher les premières lignes après nettoyage
print("\nData3 - Nettoyée après séparation:")
print(data3_clean.head())

print("\nData4 - Nettoyée après séparation:")
print(data4_clean.head())

Colonnes de data3_clean après nettoyage (avant correction):
Index(['Country NameCountry CodeIndicator NameIndicator Code1960196119621963196419651966196719681969197019711972197319741975197619771978197919801981198219831984198519861987198819891990199119921993199419951996199719981999200020012002200320042005200620072008200920102011201220132014201520162017201820192020202120222023'], dtype='object')

Colonnes de data4_clean après nettoyage (avant correction):
Index(['Country NameCountry CodeIndicator NameIndicator Code1960196119621963196419651966196719681969197019711972197319741975197619771978197919801981198219831984198519861987198819891990199119921993199419951996199719981999200020012002200320042005200620072008200920102011201220132014201520162017201820192020202120222023'], dtype='object')

Colonnes de data3_clean après séparation:
Index(['Country NameCountry CodeIndicator NameIndicator Code1960196119621963196419651966196719681969197019711972197319741975197619771978197919801981198219831984198519861987198819891990199119921993199419951996199719981999200020012002200320042005200620072008200920102011201220132014201520162017201820192020202120222023'], dtype='object')

Colonnes de data4_clean après séparation:
Index(['Country NameCountry CodeIndicator NameIndicator Code1960196119621963196419651966196719681969197019711972197319741975197619771978197919801981198219831984198519861987198819891990199119921993199419951996199719981999200020012002200320042005200620072008200920102011201220132014201520162017201820192020202120222023'], dtype='object')

Data3 - Nettoyée après séparation:
  Country NameCountry CodeIndicator NameIndicator Code1960196119621963196419651966196719681969197019711972197319741975197619771978197919801981198219831984198519861987198819891990199119921993199419951996199719981999200020012002200320042005200620072008200920102011201220132014201520162017201820192020202120222023
0  Aruba,"ABW","Dépenses publiques en éducation (...
1  ,"AFE","Dépenses publiques en éducation (% du ...
2  Afghanistan,"AFG","Dépenses publiques en éduca...
3  ,"AFW","Dépenses publiques en éducation (% du ...
4  Angola,"AGO","Dépenses publiques en éducation ...

Data4 - Nettoyée après séparation:
  Country NameCountry CodeIndicator NameIndicator Code1960196119621963196419651966196719681969197019711972197319741975197619771978197919801981198219831984198519861987198819891990199119921993199419951996199719981999200020012002200320042005200620072008200920102011201220132014201520162017201820192020202120222023
0  Aruba,"ABW","PIB par habitant ($ US courants)"...
1  ,"AFE","PIB par habitant ($ US courants)","NY....
2  Afghanistan,"AFG","PIB par habitant ($ US cour...
3  ,"AFW","PIB par habitant ($ US courants)","NY....
4  Angola,"AGO","PIB par habitant ($ US courants)...

In [20]:
# Affichage des colonnes avant la séparation pour vérification
print("\nColonnes avant séparation (data3_clean) :")
print(data3_clean.columns)

print("\nColonnes avant séparation (data4_clean) :")
print(data4_clean.columns)

# Nous allons identifier la portion de la colonne qui correspond aux noms des variables et aux années
# Pour cela, nous allons diviser la chaîne de caractères en fonction des positions des années (par exemple 1960, 1961, etc.)

# Trouver où commence les années (c'est-à-dire les premières années de données)
years_start = [str(year) for year in range(1960, 2024)]

# Séparer les colonnes basées sur les années
def separate_columns(df, years_start):
    # Trouver la position où les années commencent
    columns = df.columns[0]
    for year in years_start:
        if str(year) in columns:
            break
    
    # Découper la colonne en utilisant ce point de séparation
    part1 = columns[:columns.index(str(year))]
    part2 = columns[columns.index(str(year)):]
    
    # Assigner les nouvelles colonnes
    new_columns = part1.split(',') + part2.split(',')
    return new_columns

# Appliquer la séparation des colonnes
data3_clean.columns = separate_columns(data3_clean, years_start)
data4_clean.columns = separate_columns(data4_clean, years_start)

# Affichage des nouvelles colonnes
print("\nColonnes après séparation (data3_clean) :")
print(data3_clean.columns)

print("\nColonnes après séparation (data4_clean) :")
print(data4_clean.columns)

# Nettoyage des colonnes
data3_clean.columns = data3_clean.columns.str.replace(r'"|,', '', regex=True).str.strip()
data4_clean.columns = data4_clean.columns.str.replace(r'"|,', '', regex=True).str.strip()

# Renommer les colonnes 'Country Name' et 'Indicator Name' en 'Country' et 'Indicator' respectivement
data3_clean.rename(columns={'Country Name': 'Country', 'Indicator Name': 'Indicator'}, inplace=True)
data4_clean.rename(columns={'Country Name': 'Country', 'Indicator Name': 'Indicator'}, inplace=True)

# Afficher les premières lignes après nettoyage
print("\nData3 - Nettoyée après séparation:")
print(data3_clean.head())

print("\nData4 - Nettoyée après séparation:")
print(data4_clean.head())

Colonnes avant séparation (data3_clean) :
Index(['Country NameCountry CodeIndicator NameIndicator Code1960196119621963196419651966196719681969197019711972197319741975197619771978197919801981198219831984198519861987198819891990199119921993199419951996199719981999200020012002200320042005200620072008200920102011201220132014201520162017201820192020202120222023'], dtype='object')

Colonnes avant séparation (data4_clean) :
Index(['Country NameCountry CodeIndicator NameIndicator Code1960196119621963196419651966196719681969197019711972197319741975197619771978197919801981198219831984198519861987198819891990199119921993199419951996199719981999200020012002200320042005200620072008200920102011201220132014201520162017201820192020202120222023'], dtype='object')

ValueError: Length mismatch: Expected axis has 1 elements, new values have 2 elements

In [22]:
data1.info()
data2.info()
data3.info()
data4.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 36 entries, 0 to 35
Data columns (total 2 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Category           36 non-null     object
 1   Dépenses de santé  36 non-null     object
dtypes: object(2)
memory usage: 708.0+ bytes
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 36 entries, 0 to 35
Data columns (total 2 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   Category                         36 non-null     object
 1   Espérance de vie à la naissance  36 non-null     object
dtypes: object(2)
memory usage: 708.0+ bytes
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 266 entries, 0 to 265
Data columns (total 1 columns):
 #   Column                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          Non-Null Count  Dtype
---  ------                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          --------------  -----
 0   Country Name,"Country Code","Indicator Name","Indicator Code","1960","1961","1962","1963","1964","1965","1966","1967","1968","1969","1970","1971","1972","1973","1974","1975","1976","1977","1978","1979","1980","1981","1982","1983","1984","1985","1986","1987","1988","1989","1990","1991","1992","1993","1994","1995","1996","1997","1998","1999","2000","2001","2002","2003","2004","2005","2006","2007","2008","2009","2010","2011","2012","2013","2014","2015","2016","2017","2018","2019","2020","2021","2022","2023",  266 non-null    object
dtypes: object(1)
memory usage: 2.2+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 266 entries, 0 to 265
Data columns (total 1 columns):
 #   Column                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          Non-Null Count  Dtype
---  ------                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          --------------  -----
 0   Country Name,"Country Code","Indicator Name","Indicator Code","1960","1961","1962","1963","1964","1965","1966","1967","1968","1969","1970","1971","1972","1973","1974","1975","1976","1977","1978","1979","1980","1981","1982","1983","1984","1985","1986","1987","1988","1989","1990","1991","1992","1993","1994","1995","1996","1997","1998","1999","2000","2001","2002","2003","2004","2005","2006","2007","2008","2009","2010","2011","2012","2013","2014","2015","2016","2017","2018","2019","2020","2021","2022","2023",  266 non-null    object
dtypes: object(1)
memory usage: 2.2+ KB

In [23]:
data3.head()

  Country Name,"Country Code","Indicator Name","Indicator Code","1960","1961","1962","1963","1964","1965","1966","1967","1968","1969","1970","1971","1972","1973","1974","1975","1976","1977","1978","1979","1980","1981","1982","1983","1984","1985","1986","1987","1988","1989","1990","1991","1992","1993","1994","1995","1996","1997","1998","1999","2000","2001","2002","2003","2004","2005","2006","2007","2008","2009","2010","2011","2012","2013","2014","2015","2016","2017","2018","2019","2020","2021","2022","2023",
0  Aruba,"ABW","Dépenses publiques en éducation (...
1  ,"AFE","Dépenses publiques en éducation (% du ...
2  Afghanistan,"AFG","Dépenses publiques en éduca...
3  ,"AFW","Dépenses publiques en éducation (% du ...
4  Angola,"AGO","Dépenses publiques en éducation ...